//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;

public class Composite : IComponent
{
    private List<IComponent> children;

    public Composite()
    {
        children = new List<IComponent>();
    }

    public virtual void Add(IComponent component)
    {
        children.Add(component);
    }

    public virtual void Remove(IComponent component)
    {
        children.Remove(component);
    }

    public void Move(Point newPosition)
    {
        foreach (var component in this.children)
        {
            component.Move(newPosition);
        }
    }

    public void Resize(int newWidth, int newHeight)
    {
        throw new NotImplementedException();
    }
}

