//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Composite : IComponent
{
	public virtual object Children
	{
		get;
		set;
	}

	public virtual void Add(IComponent Component)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Remove(IComponent Component)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Draw()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Move()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Resize()
	{
		throw new System.NotImplementedException();
	}

}

