//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Shapes;

public class MyRectangle : GeometryObjectBase
{
    public Rectangle Rectangle
    {
        get
        {
            return base.shape as Rectangle;
        }

        private set;
    }

    public override void Add(IComponent component)
    {
        throw new NotImplementedException();
    }

    public override void Remove(IComponent component)
    {
        throw new NotImplementedException();
    }

    public override void Draw()
    {
        throw new NotImplementedException();
    }
}

