//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class GeometryObjectBase : ICloneable, IComponent
{
	public virtual int Width
	{
		get;
		set;
	}

	public virtual int Height
	{
		get;
		set;
	}

	public virtual Pen Pen
	{
		get;
		set;
	}

	public virtual object Position : Point
	{
		get;
		set;
	}

	public virtual ICloneable Clone()
	{
		throw new System.NotImplementedException();
	}

	public abstract void Add(IComponent Component);

	public abstract void Remove(IComponent Component);

	public abstract void Draw();

	public abstract void Move();

	public abstract void Resize();

}

