//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;

public interface IComponent
{
	void Add(IComponent Component);

	void Remove(IComponent Component);

	void Move(Point newPosition);

	void Resize(int newWidth, int newHeight);
}

