//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IComponent  : IDrawable
{
	void Add(IComponent Component);

	void Remove(IComponent Component);

	void Move();

	void Resize();

}

